script: bundle exec rake build
rvm:
- ruby-2.3.7
- ruby-2.4.4
- ruby-2.5.1
- ruby-head
- jruby-head
deploy:
- provider: rubygems
  gemspec: rspec-json_helpers.gemspec
  skip_cleanup: true
  api_key:
    secure: "YCiNDaQRgfjGJAfjYLVMMxr+Dg8TcPCYVeYEeX74IHzPP0TK1YuEmIA81RmeoF9EzyDfc+70/0qx/4UeIM6ipGtZ1kFTQssIoORObL27VAIhTn4BRN/jeet92r5VYy1WonnvGje7dSPI90MrcV95fTkmUnbAuqYGrH0TVv955MCXqMgGjOXp3HIiQBXvoMsT6wQyXt3g/FNr8IkhqezirqCgkZcS304kKtg56/p5N9WBkYKGma4Q3f4gswySPyIvJWGnHWFDjmXEbapxEgji/1N4r095OpKaSY4P9ptrcTyEGyZ9A4TxYU79vNB60/FdRZR3jPaYxUbOgyThFl3HHMylN3tX+7on75CHpW5OURJv4dQpUK66ciytr10S2Jrtf7vsH0HMvHa6hCWTbHfiLdiRcXp8JrAaNqzjKSk7SWzJ6IZsSxpuDeWHphcKMpZO1MJ8aCjsXJO4ApDVjk8JHULgjFpb5kDb5n+JWubDYiyW3t2w+y3CTCBYfuQt9SBnbL/2JOog6ryOPBevBOdt9pnKnIw78FbjCIz7dSNlo1kpZSXRLrLrcjqUFjrGBZVeAVhMwokPK524pU+ulkhJ3mO0hFdL1sqpBB2i5cgpqk9GhAWf7KZ9tccdDY/yYFjkPl8RW01H28/ddrufTcRj/I7pjpBvdFCVO+r3F44yUiA="
  on:
    ruby: ruby-2.5.1
    branch: master
    tags: true
- provider: releases
  skip_cleanup: true
  fileglob: true
  file:
  - docs.tgz
  - rspec-json_helpers-*.gem
  api_key:
    secure: "kUsHw2DOsr+PknObdmtFfakSchqfs6IbbETO3M6IieqlqxfEBDjwMRYkpxxGKdHdP6jC+KuL5caAaNB8n0icRmENismUs75HN10+dSYPKvc6Jtn9aR458YQQsM6w66YjrBEbmQaJykCFfaJ7D32ae2mSwLj5Ieb4/l0cNzR/9mruXxMIthcJcz/lEOTvwkXKT473+cUQ0P371Nd+uhDmVZuzu3i+Z8/9FT3eO/Q/JE/MaL0rTpR5AOBVeExJ5AQ8/Vvt/U9M49eF3V413mTQH56eNk+O4wx7e7Xjd5srglTAuR1yyOWqxCsM93Mb5KsQn/dRTgoJYUb7HxBxhGZezblbbM4uESslhFURyQ2XIMellxNJZV7ytVbDrJ5pe6sgcP9fvMTR48KjIFze8RlD7r170mKwlokzIdoui+/WG0cVYdMdqNKZiaNC4G8aL/PloIuqPn+MgS2uIR1vQ613muiE24+kH0ZlFplvxb5OzgtHpkcXlfEzPcDYER8uJYevNRMWQ38OU1hCDsQIbcXBbIhGDW1hAPARdqPo5UTYyVXWj0fvvdwBzqtn/zgKJKGt8U4aI+1QZEJSWd25l//B256jrenbK7k9XqCh/+YCBzp8mk3FIDOI+M55jz7SnKqVq2YJtmb7wffEKu3NfNxwuMROaxfIrCMWIlcCbadODiE="
  on:
    ruby: ruby-2.5.1
    repo: theincognitocoder/rspec-json_helpers
    branch: master
    tags: true
