script: bundle exec rake build
rvm:
- ruby-2.3.7
- ruby-2.4.4
- ruby-2.5.1
- ruby-head
- jruby-head
deploy:
- provider: rubygems
  gemspec: rspec-json_helpers.gemspec
  skip_cleanup: true
  api_key:
    secure: iuHCB3xWwSrJ6R6bE7e06TJbVKnE6u7QyHFIW5lXMk7oELxdZjGJw4UVkmhsNab1WMi9UolaRku0CbkmH2wkaLi7gOKF8tasyKt5HS2lcdZw+hS+4wRQ0oMQNFiDoU03TUe9ZucWtWzu+vlHRA7dvSCrexptupTvOFqZSz+3r3oLOkP1G84T7LQZNyKoGylhKqsLZxpQ55xjwM1fKgeIM18j2fd3PoaqWbbp/fLv2vQYus0CCy/qNrqqygxzAzSWd8hVWLGhsXZgXINL6mwTkrWSs/VOiuIcr4rmb08PYCujPj56iI0QA50oo47rnzWtYUxvwtJNMhOs2KrTOWrmST49dE/g/920eE2n1StuL2FaCxczNBHsW82QzClroE1fDxq3dcGPs17PCtDnxsAIPU6SQ3zdQTKRE8676dO0MUX388OPOUxuVLSW0GWg2LCQI8PDgnQHFTdTpyE+Ic2YYxmSElfEbB4AwUuAwT4CEoym8trFiZSfdJ1llhjIQyxFWop3l0FQtBUn5RPOMnkz6DMvwwNVvKpZYLwbC+rtCZh9a9kwl/5Vv8i6pFZlTIiU/yw7Lgd4LaOorOvJ9pcCYmL6OKPdUSNo3SMUpJl0yH1FiGXPa7IDdpp3dgW9zYGrQNNMtmkKpRf5oqOqeO1z3ReVXS6jRsFWCexuz0O7zAA=
  on:
    ruby: ruby-2.5.1
    branch: master
    tags: true
- provider: releases
  skip_cleanup: true
  fileglob: true
  file:
  - docs.tgz
  - rspec-json_helpers-*.gem
  api_key:
    secure: Bwz3M7qU+9LVjNes9zGf2gPRH6zTTsP6PmT4Is5Va9YvcEj9IqjQGkuA0P1XcnpSCuH7jQ4WM3aym2zHMZ2cq7tZ8Zw+Ui9MhQ9Zgtzj53s2at+3JTZ1LTVX5F9SG/wAyk0UT38hsIGiaChl3x2/IBnkOnC7x9f895ks6zfDZNYvo4WN35T8B28nN2B5L5wlum7K5UXQg8zM22tJLfXP3YNQVMWYbYMfXQVMU1jVCYlzPSswoMzi6PesiRwL5RelUXyTtNEfMWb092bqVvWNm14HRVi/XyrzNy+VIE9C0llH5Jlmc2d92XmDTkO8QDfiEwmXHlPpDUkIomdilKWHftjMx4sTtB3UYGG8LtYqySTyoyPrRLX+1osfE+xIi2HmDn6SEapoRRb6xkJatAN7w30fHxlzsZ+TO0u+xM6HR7QWJftSDLPt1YtZ0CNbTJyFET89w454oM0lK4fQlr8FXp2JYjAnfTr26n9Wl+qbCzlLA65GkVYZPf2gK7iN9+cMQ/CUmDx7XbvPMQjECobpyjM43vfAIA1IATISWPa7Qnex76d4PiJl42ysddppwxo4QmaPrk99lrXAAO/dgzmGt+BBMK7tAZpJqGFuj9SMSBPi3kwamM0DcGckAt44a5d0ymk5B7y0kX0bHcplhHkz7it6aQLo+hRoCgyFRFG+9jk=
  on:
    ruby: ruby-2.5.1
    repo: theincognitocoder/rspec-json_helpers
    branch: master
    tags: true
